language: go
sudo: false

matrix:
  include:
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: 1.14.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet .
  - go test -v ./...
